### ISSUE TITLE
Even if the folder is renamed, there is an error saying the icon theme Atom One Dark is missing in MATE

### ISSUE THREAD

**Issue by Poikilos** [UnnatShaneshwar/AtomOneDarkTheme#1]
Tried:
```
cd ~/.themes && git clone https://github.com/UnnatShaneshwar/AtomOneDarkTheme.git
mv AtomOneDarkTheme "Atom One Dark"
```

Choosing the theme in MATE causes:
"This theme will not look as intended because the required icon theme 'Atom One Dark' is not installed."

**Comment by UnnatShaneshwar** [comment]
The theme optionally requires the atom one dark icon theme (which is just a color modification on the papirus icon theme) 
you can get it here - https://github.com/UnnatShaneshwar/AtomOneDarkIcons
move it to ~/.icons or ~/.local/share/icons or /usr/share/icons

I'm sorry for not mentioning that.
